### ISSUE TITLE
Glitch when blurring tags field

### ISSUE THREAD

**Issue by BramGrammer** [developit/tags-input#16] opened 2016-06-16 11:44 UTC
When the mouse is clicked outside the tags area, the tags highlight in red for a split second, before returning to normal.

**Comment by BramGrammer** [comment] 2016-06-16 11:49
just realized this is because its a wrong tag, the thing is, I can still post my form. At first there was an error message, but it would disappear instantly.

**Comment by developit** [comment] 2016-06-16 12:32
Are you using the `pattern` attribute for validation, or is this just for duplicate rags?

**Comment by BramGrammer** [comment] 2016-06-16 12:33
I was using the pattern, since it came from the example, but I removed it, and it's still doing it.

**Comment by developit** [comment] 2016-06-16 12:36
Just so I'm following correctly - the issue is that submitting the form includes the invalid tag?

**Comment by BramGrammer** [comment] 2016-06-16 13:42
What happens is that whenever you leave the tags container (blur), the invalid tag is included for a split second, this results in the red color showing up really short.

**Comment by BramGrammer** [comment] 2016-06-16 14:05
upon further inspection, it appears the class dupe is added to the `span` tag with `data-tag="tag"`

I think this happens because when you leave the input field, it checks if there already is a tag like it, which there is, because that tag hasn't been removed yet. That's as far as I could see at least.

**Comment by developit** [comment] 2016-06-16 14:20
Leaving the field via blur actually commits the tag you were typing, same as pressing enter.  This sort-of seems like the intended behavior - it was done because users would leave their last tag as text in the field otherwise, and it would not be committed and sent with a form.

**Comment by developit** [comment] 2016-06-16 14:22
Ahh nevermind, I totally see what you're seeing.  When you leave the field, even without a value currently typed, all of the existing tags turn red.  Good catch, I'll try to get a fix in for that.

**Comment by BramGrammer** [comment] 2016-06-16 14:35
No probz, Amazing work btw. This code should be default in HTML, it's great to have for a cms, as I'm in the middle of developing one!

**Comment by developit** [comment] 2016-06-16 15:19
Thanks for the praise 😊 
The fix is released as version `1.1.1` 🎉

**Closed as completed** 2016-06-16 15:19 UTC
Labels: bug
